hotel_management/hms/urls.py
from django.urls import path
from . import views


app_name = "hms"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register, name="register"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("dashboard/", views.dashboard, name='dashboard'),
    path("rooms/", views.our_rooms, name="rooms"),
    path("allrooms/", views.allrooms, name="allrooms"),
    path("details/<int:room_id>/", views.room_detail, name="room_detail"),
]

hotel_management/hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hms.urls")),
    path("hms/", include("hms.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_management/templates/main/all_rooms.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Our Rooms {% endblock %}



{% block content %}

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    {% include 'includes/header1.html' %}
    {% include 'includes/header2.html' %}



    <!-- Breadcrumb Section Begin -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Our Rooms</h2>
                        <div class="bt-option">
                            <a href="{% url 'hms:index' %}">Home</a>
                            <span>Rooms</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- Rooms Section Begin -->
    <section class="rooms-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{% static 'img/room/room-1.jpg' %}" alt="">
                        <div class="ri-text">
                            <h4>Premium King Room</h4>
                            <h3>Rs 1500<span>/Pernight</span></h3>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 3</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hms:room_detail' 1 %}" class="primary-btn">More Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{% static 'img/room/room-2.jpg' %}" alt="">
                        <div class="ri-text">
                            <h4>Deluxe Room</h4>
                            <h3>Rs 1500<span>/Pernight</span></h3>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 5</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hms:room_detail' 1 %}" class="primary-btn">More Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{% static 'img/room/room-3.jpg' %}" alt="">
                        <div class="ri-text">
                            <h4>Double Room</h4>
                            <h3>Rs 1500<span>/Pernight</span></h3>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 2</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hms:room_detail' 1 %}" class="primary-btn">More Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{% static 'img/room/room-4.jpg' %}" alt="">
                        <div class="ri-text">
                            <h4>Luxury Room</h4>
                            <h3>Rs 2500<span>/Pernight</span></h3>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 1</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hms:room_detail' 1 %}" class="primary-btn">More Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{% static 'img/room/room-5.jpg' %}" alt="">
                        <div class="ri-text">
                            <h4>Room With View</h4>
                            <h3>Rs 1200<span>/Pernight</span></h3>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 1</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hms:room_detail' 1 %}" class="primary-btn">More Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{% static 'img/room/room-6.jpg' %}" alt="">
                        <div class="ri-text">
                            <h4>Small View</h4>
                            <h3>Rs 1200<span>/Pernight</span></h3>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Size:</td>
                                        <td>30 ft</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Capacity:</td>
                                        <td>Max persion 2</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>King Beds</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hms:room_detail' 1 %}" class="primary-btn">More Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="room-pagination">
                        <a href="#">1</a>
                        <a href="#">2</a>
                        <a href="#">Next <i class="fa fa-long-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Rooms Section End -->

{% include 'includes/footer.html' %}

{% endblock %}

hotel_management/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Details {% endblock %}


{% block content %}


    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    {% include 'includes/header1.html' %}
    {% include 'includes/header2.html' %}



    <!-- Contact Section Begin -->
    <section class="contact-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="contact-text">
                        <h2>Contact Info</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                        <table>
                            <tbody>
                                <tr>
                                    <td class="c-o">Address:</td>
                                    <td>Electrocom Pratap Nagar Market, Chittorgarh, Rajasthan</td>
                                </tr>
                                <tr>
                                    <td class="c-o">Phone:</td>
                                    <td>(+91) 941-411-0473</td>
                                </tr>
                                <tr>
                                    <td class="c-o">Email:</td>
                                    <td>electrocomchittor@yahoo.com</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-7 offset-lg-1">
                    <form action="#" class="contact-form">
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" placeholder="Your Name">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" placeholder="Your Email">
                            </div>
                            <div class="col-lg-12">
                                <textarea placeholder="Your Message"></textarea>
                                <button type="submit">Submit Now</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3619.5297516877113!2d74.61635881492718!3d24.8799055840448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3968a040243d9d83%3A0x5a41a84970dff5da!2sElectrocom!5e0!3m2!1sen!2sin!4v1680027131257!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>

        </div>
    </section>
    <!-- Contact Section End -->

{% include 'includes/footer.html' %}

{% endblock %}

hotel_management/templates/main/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} dashboard {% endblock %}



{% block content %}

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    {% include 'includes/header1.html' %}
    {% include 'includes/header2.html' %}

    <!-- Breadcrumb Section Begin -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>My Bookings</h2>
                        <div class="bt-option">
                            <a href="{% url 'hms:index' %}">Home</a>
                            <span>Rooms</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->


    <div class="container">
      {% include 'includes/messages.html' %}
        <div class="">
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Room No</th>
                    <th>Room Type</th>
                    <th>Name</th>
                    <th>Check in Date</th>
                    <th>Check out Date</th>
                    <th>Price</th>
                    <th>Action</th>
                    <th>Cancel</th>
                  </tr>
                </thead>
                <tbody>
                  {% for booking in my_bookings %}
                    <tr>
                      <td>{{ booking.room.room_no }}</td>
                      <td>{{ booking.room.room_type|upper }}</td>
                      <td>{{ booking.user|capfirst  }}</td>
                      <td>{{ booking.check_in_date }}</td>
                      <td>{{ booking.check_out_date }}</td>
                      <td>{{ booking.room.price }}</td>
                      <td><a class="btn btn-primary" href="{% url 'hms:room_detail' booking.room.id %}">View Your Room</a></td>
                      <!-- <td><a class="btn btn-danger" href="{% url 'hms:room_detail' booking.room.id %}">Cancel Booking</a></td> -->
                      <td><a class="btn btn-danger" href="#">Cancel Booking</a></td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td colspan="6">Start booking now to see your upcoming reservations here!</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>

        <div class="room-pagination mb-5">
            <a href="#">1</a>
            <a href="#">2</a>
            <a href="#">Next <i class="fa fa-long-arrow-right"></i></a>
        </div>
    </div>

{% include 'includes/footer.html' %}

{% endblock %}

hotel_management/templates/main/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login {% endblock %}


{% block content %}
    <div class="container mt-5">

        <h2 class="mb-2">Login</h2>

        <form method="post">
            {% csrf_token %}
            <div class="row mt-4">
                <div class="col-md-5 border p-4">
                    <p>{{ login_form.uname|as_crispy_field }}</p>
                    <p>{{ login_form.password|as_crispy_field }}</p>
                    <div class="my-2"><small class="text-muted">Don't have an account? <a href="{% url 'hms:register' %}">register</a></small></div>

                    {% include 'includes/messages.html' %}
                    <button type="submit" class="btn btn-primary btn-sm">Login</button>
                </div>
            </div>
        </form>

    </div>
{% endblock %}

hotel_management/templates/main/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Register {% endblock %}


{% block content %}
    <div class="container mt-5 py-4">
        <h2>Registration Page</h2>

        <form method="post">
            {% csrf_token %}
            <div class="row mt-4">
                <div class="col-md-5 border p-4">
                    <p>{{ register_form.username|as_crispy_field }}</p>
                    <p>{{ register_form.email|as_crispy_field }}</p>
                    <p>{{ register_form.password1|as_crispy_field }}</p>
                    <p>{{ register_form.password2|as_crispy_field }}</p>
                    <div class="my-2"><small class="text-muted">Already have an account? <a href="{% url 'hms:login' %}">login</a></small></div>
                    <button type="submit" class="btn btn-warning btn-sm">Register</button>
                </div>
            </div>
        </form>


    </div>
{% endblock %}

hotel_management/templates/main/room_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Details {% endblock %}


{% block content %}


    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    {% include 'includes/header1.html' %}
    {% include 'includes/header2.html' %}


    <!-- Breadcrumb Section Begin -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Our Rooms</h2>
                        <div class="bt-option">
                            <a href="{% url 'hms:index' %}">Home</a>
                            <span>Rooms</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->


    <!-- Room Details Section Begin -->
    <section class="room-details-section spad">
        <div class="container">

            <div class="row">
                <div class="col-lg-8">
                    <div class="room-details-item">
                        <img src="{% static 'img/room/room-details.jpg' %}" alt="">
                        <div class="rd-text">
                            <div class="rd-title">
                                <h3>Premium King Room</h3>
                                <div class="rdt-right">
                                    <div class="rating">
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star-half_alt"></i>
                                    </div>

                                    {% if user.is_authenticated %}
                                    <form action="{% url 'hms:room_detail' room_id %}" method="post" id="myForm">
                                        {% csrf_token %}
                                        <input type="hidden" name="book_now_button" value="book_now_button">
                                        <a id="book_now">Booking Now</a>
                                    </form>
                                    {% endif %}


                                </div>
                            </div>
                            <h2>Rs {{room.price}}<span> /per-night</span></h2>
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="r-o">Room No:</td>
                                        <td>{{room.room_no}}</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Room Type:</td>
                                        <td>{{room.room_type|upper}}</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Bed:</td>
                                        <td>{{ room.beds }}</td>
                                    </tr>
                                    <tr>
                                        <td class="r-o">Services:</td>
                                        <td>Wifi, Television, Bathroom,...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <p class="f-para">
                                {{room.description}}
                            </p>
                        </div>
                    </div>

                    <!-- Reviews Section Start -->
                    <div class="rd-reviews">
                        <h4>Comments</h4>

                        {% for comment in comments %}
                        <div class="review-item">
                            <div class="ri-pic">
                                <img src="{% static 'img/room/avatar/avatar.webp' %}" alt="">
                            </div>
                            <div class="ri-text">
                                <span>{{ comment.created_at }}</span>
                                <h5>{{ comment.user.username }}</h5>
                                <p>{{ comment.comment }}</p>
                            </div>
                        </div>
                        {% empty %}
                        <div class="review-item">
                            <div class="ri-text">
                                NO Comments Yet
                            </div>
                        </div>
                        {% endfor %}


                    </div>

                    {% if user.is_authenticated %}
                    <div class="review-add">
                        <h4>Add Comments</h4>
                        <form action="{% url 'hms:room_detail' room_id %}" method="post" class="ra-form">
                            {% csrf_token %}
                            <input type="hidden" value="comment_button" name="comment_button">
                            <div class="row">
                                <div class="col-lg-6">
                                    <input type="text" name="name" placeholder="Name*">
                                </div>
                                <div class="col-lg-6">
                                    <input type="text" name="email" placeholder="Email*">
                                </div>
                                <div class="col-lg-12">
                                    <textarea name="message" placeholder="Your Comment"></textarea>
                                    <button type="submit">Submit Now</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    {% endif %}
                    <!-- Reviews Section End -->


                </div>
                <div class="col-lg-4">
                    <div class="room-booking">
                        <h3>Your Reservation</h3>

                        <form action="{% url 'hms:index' %}" method="post">
                            {% csrf_token %}
                            <div class="check-date">
                                <label for="date-in">Check In:</label>
                                <input type="text" class="date-input" name="check_in_date" id="date-in" required>
                                <i class="icon_calendar"></i>
                            </div>
                            <div class="check-date">
                                <label for="date-out">Check Out:</label>
                                <input type="text" class="date-input" name="check_out_date" id="date-out" required>
                                <i class="icon_calendar"></i>
                            </div>
                            <div class="select-option">
                                <label for="guest">Room Type:</label>
                                <select id="guest" name="room_type" required>
                                    <option value="ac">AC</option>
                                    <option value="nonac">Non AC</option>
                                </select>
                            </div>
                            <div class="select-option">
                                <label for="room">Bed:</label>
                                <select id="room" name="no_of_beds">
                                    <option value="0">Select an Option</option>
                                    <option value="1">Single bed</option>
                                    <option value="2">Double Room</option>
                                    <option value="3">Tripe Room</option>
                                </select>
                            </div>
                            <button type="submit">Check Availability</button>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- Room Details Section End -->

{% include 'includes/footer.html' %}

{% endblock %}


{% block extra_js %}
    <script>
        book_now = document.querySelector('#book_now')
        myForm = document.querySelector('#myForm')
        book_now.addEventListener('click', ()=>{
            myForm.submit();
        })
    </script>
{% endblock %}

hotel_management/templates/main/rooms.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Rooms {% endblock %}



{% block content %}

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    {% include 'includes/header1.html' %}
    {% include 'includes/header2.html' %}

    <!-- Breadcrumb Section Begin -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Available Rooms</h2>
                        <div class="bt-option">
                            <a href="{% url 'hms:index' %}">Home</a>
                            <span>Rooms</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->


    <div class="container">
        <div class="">
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Room No</th>
                    <th>Room Type</th>
                    <th>Beds</th>
                    <th>Price</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for room in available_rooms %}
                    <tr>
                      <td>{{ room.room_no }}</td>
                      <td>{{ room.room_type|upper }}</td>
                      <td>{{ room.beds }}</td>
                      <td>{{ room.price }}</td>
                      <td>{{ room.room_status|capfirst }}</td>
                      <td>
                        <div>
                          <form method="post" action="{% url 'hms:rooms' %}">
                            {% csrf_token %}
                            <input type="hidden" name="room_id" value="{{room.id}}">

                            {% if user.is_authenticated %}
                              <button type="submit" class="btn btn-warning" >Book Now</button>
                            {% endif %}
                            <a class="btn btn-primary" href="{% url 'hms:room_detail' room.id %}">View</a>
                          </form>
                        </div>
                      </td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td colspan="6">No rooms available for the selected dates.</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>

        <div class="room-pagination mb-5">
            <a href="#">1</a>
            <a href="#">2</a>
            <a href="#">Next <i class="fa fa-long-arrow-right"></i></a>
        </div>
    </div>

{% include 'includes/footer.html' %}

{% endblock %}