hotel_management/hms/urls.py
from django.urls import path
from . import views


app_name = "hms"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register, name="register"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("dashboard/", views.dashboard, name='dashboard'),
    path("rooms/", views.our_rooms, name="rooms"),
    path("allrooms/", views.allrooms, name="allrooms"),
    path("details/<int:room_id>/", views.room_detail, name="room_detail"),
]

hotel_management/hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hms.urls")),
    path("hms/", include("hms.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_management/templates/includes/footer.html
{% load static %}
<!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="footer-text">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="ft-about">
                            <div class="logo">
                                <a href="#">
                                    <img src="{% static '' %}" alt="footer-logo">
                                </a>
                            </div>
                            <p>We inspire and reach millions of travelers<br /> across 90 local websites</p>
                            <div class="fa-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-tripadvisor"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1">
                        <div class="ft-contact">
                            <h6>Contact Us</h6>
                            <ul>
                                <li>(+91) 941-411-0473</li>
                                <li>electrocomchittor@yahoo.com</li>
                                <li>Electrocom Pratap Nagar Market, Chittorgarh (Rajasthan)</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1">
                        <div class="ft-newslatter">
                            <h6>New latest</h6>
                            <p>Get the latest updates and offers.</p>
                            <form action="#" class="fn-form">
                                <input type="text" placeholder="Email">
                                <button type="submit"><i class="fa fa-send"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-option">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5">
                        <ul>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Terms of use</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Environmental Policy</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-7">
                        <div class="co-text">
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
                            <div>
                                Designed & Developed By : Electrocom, Chittorgarh (Rajasthan) - 94141-10473
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

hotel_management/templates/includes/header1.html
{% load static %}


    <!-- Offcanvas Menu Section Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="canvas-open">
        <i class="icon_menu"></i>
    </div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <i class="icon_close"></i>
        </div>
        <div class="search-icon  search-switch">
            <i class="icon_search"></i>
        </div>
        <div class="header-configure-area">
            <div class="language-option">
                <img src="{% static 'img/flag.jpg' %}" alt="">
                <span>EN <i class="fa fa-angle-down"></i></span>
                <div class="flag-dropdown">
                    <ul>
                        <li><a href="#">English</a></li>
                        <li><a href="#">Hindi</a></li>
                    </ul>
                </div>
            </div>
            <a href="#" class="bk-btn">Booking Now</a>
        </div>

        <nav class="mainmenu mobile-menu">
            <ul>
                <li class="active"><a href="{% url 'hms:index' %}">Home</a></li>
                {% if user.is_authenticated  %}
                    <li><a href="{% url 'hms:dashboard' %}">My Bookings</a></li>
                {% endif  %}
                <li><a href="{% url 'hms:about' %}">About Us</a></li>
                <li><a href="{% url 'hms:contact' %}">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="top-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-tripadvisor"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
        <ul class="top-widget">
            <li><i class="fa fa-phone"></i> (+91) 941-411-0473</li>
            <li><i class="fa fa-envelope"></i> electrocomchittor@yahoo.com</li>
        </ul>
    </div>
    <!-- Offcanvas Menu Section End -->

hotel_management/templates/includes/header2.html
{% load static %}
    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="top-nav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="tn-left">
                            <li><i class="fa fa-phone"></i> (+91) 941-411-0473</li>
                            <li><i class="fa fa-envelope"></i> electrocomchittor@yahoo.com</li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <div class="tn-right">
                            <div class="top-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-tripadvisor"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                            <div class="language-option mr-5">
                                <img src="{% static 'img/flag.jpg' %}" alt="">
                                <span>EN <i class="fa fa-angle-down"></i></span>
                                <div class="flag-dropdown">
                                    <ul>
                                        <li><a href="#">English</a></li>
                                        <li><a href="#">Hindi</a></li>
                                    </ul>
                                </div>
                            </div>
                            {% if user.is_authenticated  %}
                                <a href="{% url 'hms:logout_user' %}" class="btn btn-outline-warning">Logout</a>
                            {% else %}
                                <a href="{% url 'hms:login' %}" class="btn btn-outline-warning">Login</a>
                                <a href="{% url 'hms:register' %}" class="btn btn-outline-warning">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="menu-item">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="logo">
                            <a href="{% url 'hms:index' %}">
                                <img src="{% static '' %}" alt="LOGO">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="nav-menu">
                            <nav class="mainmenu">
                                <ul>
                                    <li class="active"><a href="{% url 'hms:index' %}">Home</a></li>
                                    <li><a href="{% url 'hms:allrooms' %}">Our Rooms</a></li>
                                    {% if user.is_authenticated  %}
                                        <li><a href="{% url 'hms:dashboard' %}">My Bookings</a></li>
                                    {% endif  %}
                                    <li><a href="{% url 'hms:about' %}">About Us</a></li>
                                    <li><a href="{% url 'hms:contact' %}">Contact</a></li>
                                </ul>
                            </nav>
                            <div class="nav-right search-switch">
                                <i class="icon_search"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>


        <!-- Search model Begin -->
        <div class="search-model">
            <div class="h-100 d-flex align-items-center justify-content-center">
                <div class="search-close-switch"><i class="icon_close"></i></div>
                <form class="search-model-form">
                    <input type="text" id="search-input" placeholder="Search here.....">
                </form>
            </div>
        </div>
        <!-- Search model end -->
    <!-- Header End -->

hotel_management/templates/includes/messages.html
{% for message in messages %}
    <div id="id" class="container">
        <div class="alert alert-{{message.tags}}" alert-dismissable role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="True">&times;</span>
            </button>
            <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Error:
                {% else %}
                    {{ message.tags | title }}
                {% endif %}
            </strong>
            {{ message }}
        </div>
    </div>
{% endfor %}